[package]
name = "auto-dungeon"
version = "0.1.0"
authors = ["ltorbay <louistorbay@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = { version = "0.35.1", features = ["gfx"] }